// <auto-generated />
using System;
using CapaInfraestructura;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CapaInfraestructura.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CapaDominio.Entities.Categorias", b =>
                {
                    b.Property<int>("NoCategoria")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("NoCategoria"));

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NombreCategoria")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("NoCategoria");

                    b.ToTable("Categorias");
                });

            modelBuilder.Entity("CapaDominio.Entities.Producto", b =>
                {
                    b.Property<int>("NoProducto")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("NoProducto"));

                    b.Property<int?>("CategoriaNoCategoria")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("NoCategoria")
                        .HasColumnType("int");

                    b.Property<string>("NombreProduto")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("PrecioVenta")
                        .HasColumnType("float");

                    b.Property<int>("Stock")
                        .HasColumnType("int");

                    b.HasKey("NoProducto");

                    b.HasIndex("CategoriaNoCategoria");

                    b.ToTable("Productos");
                });

            modelBuilder.Entity("CapaDominio.Entities.Producto", b =>
                {
                    b.HasOne("CapaDominio.Entities.Categorias", "Categoria")
                        .WithMany("Productos")
                        .HasForeignKey("CategoriaNoCategoria");

                    b.Navigation("Categoria");
                });

            modelBuilder.Entity("CapaDominio.Entities.Categorias", b =>
                {
                    b.Navigation("Productos");
                });
#pragma warning restore 612, 618
        }
    }
}
